FROM python:3.9-slim-bullseye

# Installation des dépendances du système
RUN apt-get update && apt-get install -y libpq-dev

# Installation des dépendances Python
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt