version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financial_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: .
    container_name: etl_pipeline
    command: python etl_scripts/extract_transform.py
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: financial_data
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: